version: "3.8"
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    expose:
      - "6379"
  category:
    build: 
      context: "./category"
      network: host
    ports:
      - "3003:3003"
    depends_on: 
      - redis
  post:
    build: 
      context: "./post"
      network: host
    ports:
      - "3002:3002"
    depends_on: 
      - redis
  product:
    build: 
      context: "./product"
      network: host
    ports:
      - "3001:3001"
    depends_on: 
      - redis